version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: urlshortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: urlshortener_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "npx prisma migrate dev --name init && npm run start:dev"

volumes:
  db_data:
